### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by singingwolfboy** [thehappycheese/parse_wkb#1]
What's the license for this code? If you publish it without a license, then it's proprietary by default and unusable by others.

If you're not sure, the [Choose a License](https://choosealicense.com) website can probably help.

**Comment by thehappycheese** [comment]
Hi singingwolfboy, I visited your link, I will add an MIT licence if you like? I am flattered you think it worth it for this project :)

I typically do not licence my projects as I do not understand them and I certainly make no guarantees nor accept any legal liability for them.
